### ISSUE TITLE
soooooo dope

### ISSUE THREAD

**Issue by joshuawootonn** [tedpaulsen/mac-setup#1] opened 2020-03-15 03:05 UTC

**Comment by joshuawootonn** [comment] 2020-03-15 03:06
Isn't this what gists are for????

**Comment by joshuawootonn** [comment] 2020-03-15 03:08
![](https://media.giphy.com/media/3sbZaElzV2J8ZVsSYg/giphy.gif)

**Comment by joshuawootonn** [comment] 2020-03-15 03:09
dude I love you :)

**Comment by tedpaulsen** [comment] 2020-06-27 23:23
this is a duplicate of #2 closing

**Closed by tedpaulsen** 2020-06-27 23:23 UTC
